# Set the wallpaper for all monitors
# preload = ~/Pictures/Wallpaper/The_Backwater.png
# wallpaper = ,~/Pictures/Wallpaper/The_Backwater.png
preload = ~/Pictures/Wallpaper/forest-3.jpg
wallpaper = ,~/Pictures/Wallpaper/forest-3.jpg

# Enable splash screen
splash = false

# Enable IPC for runtime control
ipc = on 
