ln -s ~/GitHub/dot_files/.config/bash/config.bash ~/.bashrc
ln -s ~/GitHub/dot_files/.config/bash/config.bash ~/.bash_profile
ln -s ~/GitHub/dot_files/.config/csh/config.csh ~/.cshrc
ln -s ~/GitHub/dot_files/.config/csh/config.csh ~/.tcshrc
ln -s ~/GitHub/dot_files/.gitconfig ~/.gitconfig
ln -s ~/GitHub/dot_files/.config/nvim ~/.vim
ln -s ~/GitHub/dot_files/.config/nvim/init.vim ~/.vimrc
ln -s ~/GitHub/dot_files/.config/nvim ~/.nvim
ln -s ~/GitHub/dot_files/.config/nvim/init.vim ~/.nvimrc
ln -s ~/GitHub/dot_files/.config/emacs/space.el ~/.spacemacs
ln -s ~/GitHub/dot_files/.inputrc ~/.inputrc
