# Set the wallpaper for all monitors (empty monitor = fallback for any unmatched)
wallpaper {
    monitor =
    path = ~/Pictures/Wallpaper/The_Backwater.png
    fit_mode = cover
}

# Disable splash screen
splash = false
