# ========================== Layout configuration ==============================

dwindle {
    pseudotile = true       # Master-like behavior
    preserve_split = true   # Keep split direction
    smart_split = false
    smart_resizing = true
}

master {
    new_status = master     # New windows become master
    new_on_top = false      # New windows go to the stack
    mfact = 0.55           # Master area ratio (55%)
}

# ============================= Window rules ===================================

# Floating =====================================================================
# Float certain windows by default
windowrule = float on, match:title Open.File
windowrule = float on, match:title Save.File
windowrule = float on, match:title File.Operation.Progress
windowrule = float on, match:class file-roller
windowrule = float on, match:class gnome-calculator

# Specific applications
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class nm-applet
windowrule = float on, match:class nm-connection-editor

# Picture-in-Picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = pin on, match:title ^(Picture-in-Picture)$

# File manager
windowrule = float on, match:class org.gnome.Nautilus
windowrule = size 1200 800, match:class org.gnome.Nautilus

# Image viewer
windowrule = float on, match:class org.gnome.Loupe
windowrule = size 1200 800, match:class org.gnome.Loupe

windowrule = float on, match:class (chrome-web.telegram).*
windowrule = size 1200 800, match:class (chrome-web.telegram).*

# Fullscreen apps ==============================================================
# Gaming applications
windowrule = fullscreen on, match:class ^(steam_app_).*
windowrule = fullscreen on, match:class gamescope

# Opacity settings =============================================================
windowrule = opacity 0.9, match:class emacs
windowrule = opacity 0.97, match:class cursor

# Terminals ====================================================================
# Float terminals by default with custom size
windowrule = float on, match:class ^(.*ghostty)
windowrule = size 1080 640, match:class ^(.*ghostty)
windowrule = opacity 0.95, match:class ^(.*ghostty)

windowrule = float on, match:class kitty
windowrule = size 1080 640, match:class kitty
windowrule = opacity 0.9, match:class kitty

windowrule = float on, match:class Alacritty
windowrule = size 1080 640, match:class Alacritty
windowrule = opacity 0.9, match:class Alacritty
