alias ys 'yum search'
alias yi 'yum info'
alias yl 'yum list'
alias ygl 'yum group list'
alias yli 'yum list installed'
alias yu 'sudo yum update'
alias yi 'sudo yum install'
alias ygi 'sudo yum groupinstall'
alias yr 'sudo yum remove'
alias ygr 'sudo yum groupremove'
alias yrl 'sudo yum remove --remove-leaves'
alias yc 'sudo yum clean all'
